apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: frontend
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       frontend
  updatePolicy:
    updateMode: "Auto"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: currencyservice
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       currencyservice
  updatePolicy:
    updateMode: "Auto"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: productcatalogservice
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       productcatalogservice
  updatePolicy:
    updateMode: "Auto"